# Battery prompt
RPROMPT='$(battery_pct_prompt)'

# Theme
ZSH_THEME="fino"

# Disable updates
zstyle ':omz:update' mode disabled

# Fzf zsh config via zstyle
zstyle ':fzf-tab:complete:cd:*' fzf-preview ''

# Plugins
plugins=(sudo battery zsh-interactive-cd fzf-tab zsh-fzf-history-search fast-syntax-highlighting zsh-you-should-use zoxide zabb)

source $HOME/.oh-my-zsh/oh-my-zsh.sh

# Broot function
function br {
    local cmd cmd_file code
    cmd_file=$(mktemp)
    if broot --outcmd "$cmd_file" "$@"; then
        cmd=$(<"$cmd_file")
        command rm -f "$cmd_file"
        eval "$cmd"
    else
        code=$?
        command rm -f "$cmd_file"
        return "$code"
    fi
}

# Add ~/.local/bin to PATH
if ! [[ "$PATH" =~ "$HOME/.local/bin:" ]]
then
    PATH="$HOME/.local/bin:$PATH"
fi
export PATH

# Add ~/.cargo/bin to PATH
if ! [[ "$PATH" =~ "$HOME/.cargo/bin:" ]]
then
    PATH="$HOME/.cargo/bin:$PATH"
fi
export PATH

# Bash completions
autoload -U bashcompinit
bashcompinit

# Pipx completions
eval "$(register-python-argcomplete pipx)"

# Zsh completions
compinit

# Zoxide
eval "$(zoxide init zsh)"

# Thefuck
eval "$(thefuck --alias)"

# Check if dinit is running, if it is not then start it
DINIT_SOCKET=/run/user/1000/dinitctl
if [[ ! -e "$DINIT_SOCKET" ]]; then
    dinit --user --quiet &
fi
