# Completions for arduino-cli and eza
fpath=($HOME/dotfiles/completions $fpath)

# Battery prompt
RPROMPT='$(battery_pct_prompt)'

# Theme
ZSH_THEME="fino"

# Disable updates
zstyle ':omz:update' mode disabled

# Fzf zsh config via zstyle
zstyle ':fzf-tab:complete:cd:*' fzf-preview ''

# Env vars
export EDITOR=nvim
export GIT_EDITOR=nvim
export SUDO_EDITOR=nano
export QT_QPA_PLATFORM=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# Plugins
plugins=(sudo battery zsh-interactive-cd fzf-tab zsh-fzf-history-search zsh-syntax-highlighting zsh-you-should-use zoxide)

source $HOME/.oh-my-zsh/oh-my-zsh.sh

# To use pnpm
export PNPM_HOME="/home/padelvi/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# Add ~/.local/bin to PATH
if ! [[ "$PATH" =~ "$HOME/.local/bin:" ]]
then
    PATH="$HOME/.local/bin:$PATH"
fi
export PATH

# Add ~/.cargo/bin to PATH
if ! [[ "$PATH" =~ "$HOME/.cargo/bin:" ]]
then
    PATH="$HOME/.cargo/bin:$PATH"
fi
export PATH

# Bash completions
autoload -U bashcompinit
bashcompinit

# Pipx completions
eval "$(register-python-argcomplete pipx)"

# Zsh completions
compinit

# Zoxide
eval "$(zoxide init zsh)"

# Thefuck
eval "$(thefuck --alias)"
