-- return {
--   {
--     "williamboman/mason-lspconfig.nvim",
--     opts = {},
--   },
--   {
--     "jay-babu/mason-null-ls.nvim",
--     opts = {
--       ensure_installed = { "prettier", "stylua" },
--     },
--   },
--   {
--     "jay-babu/mason-nvim-dap.nvim",
--     opts = {},
--   },
--   {
--     "jose-elias-alvarez/null-ls.nvim",
--     opts = function(_, config)
--       -- config variable is the default configuration table for the setup function call
--       -- local null_ls = require "null-ls"
--
--       -- Check supported formatters and linters
--       -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
--       -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
--       config.sources = {
--         -- Set a formatter
--         -- null_ls.builtins.formatting.stylua,
--         -- null_ls.builtins.formatting.prettier,
--       }
--       return config
--     end,
--   },
-- }
